### ISSUE TITLE
The Body element  style not able to update through lighting framework.

### ISSUE THREAD

**Issue by kathiravanltts** [rdkcentral/Lightning-SDK#106]
The html body element  style not able to update through lighting framework.
we need to make html body colour transparent but after build the body color is black in startApp.js.
is there any solution for this issue?

**Comment by michielvandergeest** [comment]
This issue has been addressed in PR #102 (https://github.com/rdkcentral/Lightning-SDK/pull/102/files#diff-dc8e6fa52430fd925a4f492e84b4ce3fL24) 

It will be part of the next upcoming release.

**Comment by michielvandergeest** [comment]
Released in 2.5.0 https://github.com/rdkcentral/Lightning-SDK/blob/master/CHANGELOG.md#v250
