### ISSUE TITLE
Change pages using by using numeric keyboard on routes

### ISSUE THREAD

**Issue by jhderojasUVa** [rdkcentral/Lightning-SDK#115]
I guess is a feature but I don't see it on the documentation or it's a bug.

After creating a new application by `lng create` or (on the old one) removing the node_modules/wpe-lightning*, package-lock.json and doing a `npm i` (so the versions and modules are the latest), if you do an application with routes (and on the routes file you create put them in some order) when you do the `lng dev` and the application shows on the browser, you can move show a page by pressing 1, 2, 3, 4... etc (depending of the number of pages you have an the order they are on the routes file).

Is there any way to disabling this on dev? (something to put on the settings.json file).

I have take a look in the SDK at the `src/Router/utils.js` to see the properties that are used on the routes but I don't see anything related.

**Comment by erikhaandrikman** [comment]
Can we close this issue?

**Comment by erikhaandrikman** [comment]
Can we close this issue?

**Comment by jhderojasUVa** [comment]
Jajaja, yes, of course... xDDD
