### ISSUE TITLE
Dash support for mediaplayer

### ISSUE THREAD

**Issue by krishdarling143** [rdkcentral/Lightning-SDK#119]
@g-zachar @wouterlucas 
import {Lightning, MediaPlayer} from 'wpe-lightning-sdk';
import 'dashjs/dist/dash.all.debug'

export default class DRM extends Lightning.Component {
   static _template(){
    return {
     MediaPlayer:{  type: MediaPlayer },
   
    }
  }
  
 _init(){
     console.log(dashjs)
    const video = this.tag("MediaPlayer").videoEl;   
    this.dash = dashjs.MediaPlayer().create();   
    this.dash.initialize();
    console.log(this.dash)
    this.dash.attachView(video); 
   
    
  } 
  _handleEnter(){
    this.dash.attachSource('https://dash.akamaized.net/akamai/bbb_30fps/bbb_30fps.mpd');

  }}
video is playing but not visible

**Comment by michielvandergeest** [comment]
Answering on Slack. Closing this issue to keep the repo clean from support questions
