### ISSUE TITLE
Closed Caption Support

### ISSUE THREAD

**Issue by oshepes** [rdkcentral/Lightning-SDK#153]
Is there Closed Captioning support for the VideoPlayer? if so, is there an example I can use?

**Comment by erikhaandrikman** [comment]
There is no out of the box support for Closed Caption, you might want to take a look at: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/textTracks and if you're running in a non-composited browser, you need to Render the text elements yourself
