### ISSUE TITLE
FontFace should be used in a manner allowing graceful degradation

### ISSUE THREAD

**Issue by Serhii-the-Dev** [rdkcentral/Lightning-SDK#185]
According to the [spec](https://www.w3.org/TR/css-font-loading/), FontFace API allows to load fonts in the same manner it's done in CSS. Thus, constructions like this one should be allowed:
```js
url('font.woff2') format('woff2'), url('font.woff') format('woff')
```
Unfortunately, currently FontFace constructor accepts a parameter that is wrapped with `url(...)` expression making impossible to manually specify multiple fonts formats: https://github.com/rdkcentral/Lightning-SDK/blob/f89720ac765ff47497079852d0e9102b82af8c79/src/Application/index.js#L160

**Comment by michielvandergeest** [comment]
This feature is addressed in version 4.3.0:
https://github.com/rdkcentral/Lightning-SDK/blob/master/CHANGELOG.md#v430
