### ISSUE TITLE
Router add query params

### ISSUE THREAD

**Issue by chiefcll** [rdkcentral/Lightning-SDK#206]
The router hashes should grab queryParams and add them into the Params object.

Example:
'browse/path' with ?menuUrl=someUrl

Should add { menuUrl: 'someUrl' } into the params obj.

**Comment by erikhaandrikman** [comment]
Sounds like a good addition, by default it's only available in the `boot` function: https://rdkcentral.github.io/Lightning-SDK/#/plugins/router/configuration?id=boot

We may need to encapsulate data to prevent any collision with named groups, will work on that after i merged the PR.
