### ISSUE TITLE
Settings not checking for Null values

### ISSUE THREAD

**Issue by chiefcll** [rdkcentral/Lightning-SDK#227]
https://github.com/rdkcentral/Lightning-SDK/blob/779e85aff338f812b411ab4cbcd7fe2fd7a1b9bd/src/Settings/index.js#L38

Doesn't check for null which is an object

**Comment by michielvandergeest** [comment]
In what situation have you run into the case where `obj` equals `null`?

**Comment by chiefcll** [comment]
const queryParams = new window.URLSearchParams(document.location.search);
const myValue = queryParams.get('blah')) // returns null

So any url params not defined are null

**Comment by michielvandergeest** [comment]
Got it. That's a case we haven't ran into because we usually avoid `null` values like this and use defaults instead. But I guess it's a valid use case to pass this logic down to the App code. Should be a small fix.

**Comment by chiefcll** [comment]
https://github.com/rdkcentral/Lightning-SDK/pull/228

**Comment by michielvandergeest** [comment]
Fixed in v4.3.2 (https://github.com/rdkcentral/Lightning-SDK/blob/master/CHANGELOG.md#v432)
