### ISSUE TITLE
Support of Video and Audio Players simultaneous playback.

### ISSUE THREAD

**Issue by AndriyShpyra** [rdkcentral/Lightning-SDK#232]
We investigate the possibility to play video (without audio tracks) and separate audio content in parallel on Comcast devices.
For that, we are using audio and video html5 players.
Currently, when 2 players are launched simultaneously, one will start playback and the second player will be automatically paused.
Is there a way to start playback on audio and video players simultaneously?

**Comment by erikhaandrikman** [comment]
The device can probably only handle playback of one videostream. You could investigate if the browser has support for [WebAudio api](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API) and test if you can play and audio source while playback has started

**Comment by erikhaandrikman** [comment]
Can we close this issue?

**Comment by AndriyShpyra** [comment]
@erikhaandrikman yes, thank you for your recommendations! 
we have investigated it.
