### ISSUE TITLE
Lightning Router Docs incorrect

### ISSUE THREAD

**Issue by chiefcll** [rdkcentral/Lightning-SDK#237]
http://www.lightningjs.io/docs/#/lightning-sdk-reference/plugins/router/configuration?id=accessing-data-from-route-components

As far as I can tell - the params are not added to the page instance... they are added as page.params.

https://github.com/rdkcentral/Lightning-SDK/blob/779e85aff338f812b411ab4cbcd7fe2fd7a1b9bd/src/Router/utils/provider.js#L90

**Comment by erikhaandrikman** [comment]
Thanks for pointing this out, we forgot to update that part of the documentation.

**Comment by erikhaandrikman** [comment]
Thanks for pointing this out. This was deprecated behaviour and was already updated in the docs: https://github.com/rdkcentral/Lightning-SDK/blob/master/docs/plugins/router/configuration.md#accessing-data-from-route-components but somehow the change didn't found it's way to the docs on lightningjs.io

This will be updated in the next docs release
