### ISSUE TITLE
Lightning Router removing trailing / on paths

### ISSUE THREAD

**Issue by chiefcll** [rdkcentral/Lightning-SDK#240]
<img width="713" alt="Screen Shot 2021-06-01 at 8 52 09 AM" src="https://user-images.githubusercontent.com/2090941/120326844-25911180-c2b7-11eb-8f1e-5e74110c02a7.png">

Trying to navigate to paths like: `/entity/movie/5025533520783917112/` fail due to the route not being created correctly. Its removing the trailing slash...

**Comment by erikhaandrikman** [comment]
Thanks for the bug report. The reason we strip the trailing slash is to determine how much `floors` a link has: https://github.com/rdkcentral/Lightning-SDK/blob/0accb42cf6479e711a5c604d6ccc140050b44b7d/src/Router/utils/route.js#L31 

and this is again being used to match a hash against configured routes: https://github.com/rdkcentral/Lightning-SDK/blob/0accb42cf6479e711a5c604d6ccc140050b44b7d/src/Router/utils/route.js#L40

We're now testing a fix for this issue and will notify you when it's available in master: 
https://github.com/rdkcentral/Lightning-SDK/commit/e111f4b38a134f7695369e930e47491b86550bcb

**Comment by erikhaandrikman** [comment]
Fixed in [v4.4.0](https://github.com/rdkcentral/Lightning-SDK/blob/master/CHANGELOG.md#v440)
