### ISSUE TITLE
Why is lightningjs/core dependency importing wildcard version?

### ISSUE THREAD

**Issue by xsorifc28** [rdkcentral/Lightning-SDK#265]
The dependency should be a specific version of lightningjs/core.

**Comment by michielvandergeest** [comment]
Sorry for the delayed response @xsorifc28 

You are right that normally one would tag a specific version of a dependency.

In this case the wildcard version effectively installs the latest version of Lightning Core when you create a new App project (via the Lightning-CLI for example)

**Comment by xsorifc28** [comment]
I understand the reason for wildcard, but it can lead to unexpected behavior when upgrading to latest version of the sdk.

Shouldn't each version of the sdk be tied to (at most) a minor version?
