### ISSUE TITLE
VideoPlayer plugin vs AAMP Player 

### ISSUE THREAD

**Issue by CooperCao** [rdkcentral/Lightning-SDK#266]
Hi Guys:
What is the difference between VideoPlayer plugin vs AAMP Player?

**Comment by michielvandergeest** [comment]
The VideoPlayer plugin in the SDK is nothing more than a thin wrapper to interact with a video-tag element, whereas AAMP is a piece of middleware software part of the RDK stack to actually play out the video (https://developer.rdkcentral.com/video/documentation/components/open-sourced_components/advanced_adaptive_media_player/#side-scroll-1)
