### ISSUE TITLE
Using fetch with local file path in the startApp helper

### ISSUE THREAD

**Issue by Serg-de-Adelantado** [rdkcentral/Lightning-SDK#27]
App created via CLI util with the `lng create` command will contain the `statApp` function building a launch sequence. There are two steps, `getAppMetadata` and `getSettings` that will not work without HTTP server(i.e. when launched as Tizen app up to my understanding) since those methods using the `fetch` API trying to read a file from local file system, which is not supported by this API: https://github.com/WebPlatformForEmbedded/Lightning-SDK/blob/15a54a612df9b7c21aa8f77ad114462d29761f54/src/startApp.js#L41-L50

**Comment by mattiapontonio** [comment]
Can You please provider the error?

In my experience:
- The CLI create a server that serves the apps files as they are builded (`lng build`, `lng serve`)
- The support of `fetch` API is a browser issue and should be redirected to che build process (rollup config in the CLI or custom config?). Can You find out witch browser are You using? Can You investigate a configuration for this browser in rollup?

**Comment by mattiapontonio** [comment]
Check esEnv here: https://webplatformforembedded.github.io/Lightning-SDK/#/plugins/settings
I has a similar issue related to the Enviroment.

**Comment by Serg-de-Adelantado** [comment]
@mattiapontonio this issue is related to platforms like Tizen where apps are packaged as a bundle of static files and could be launched without web server. I don't think that stand-alone mode support is top priority so this issue definitely has low priority(or even could be closed in case if such feature is not planned).

**Comment by mattiapontonio** [comment]
Sorry, I'm not aligned with your enviroment. Currently I'm developing an app that is served likes normal web apps (such as React, Vue...) and seem to works in this directon. Anyway I'm not a code contributor so I'm out of this.
Best regards
Mattia

**Comment by Serg-de-Adelantado** [comment]
@mattiapontonio the approach I've described initially could be achieved with custom build system(i.e. with use of own build system based on webpack/rollup/gulp/etc. instead of `lng` CLI). In our team we encountered this issues when tried to launch Lightning-based app on Tizen TV just out of curiosity, to check the performance(it was great, btw). So I am leaving a decision to close or keep this issue to maintainers. Thank you for your engagement and readiness to help, I really appreciate that!

**Comment by michielvandergeest** [comment]
@Serg-de-Adelantado sorry for getting back to you so late. We have released v1.6.0 of the _Lightning CLI_ which contains a new `lng dist` command (https://github.com/rdkcentral/Lightning-CLI#dist) that hopefully addresses your issue.

First a quick background: `startApp.js` dynamically loads settings and metadata, simulating the way the Metrological App Store works, during local development. But as you have noticed the use of `fetch` is not allowed when served from the local file system.

The `lng dev` command generates a distributable version of the App and doesn’t reply on `startApp.js`. But please note when the App code itself uses `fetch` or `xhr` to retrieve data, you will run into the same issue.

**Comment by Serg-de-Adelantado** [comment]
@michielvandergeest great news, thank you for this update! Brief checks shows that this feature should solve the issue. Regarding `fetch`-ing of content from app bundle, we don't have plans to use this approach in production as all data should be served through HTTP APIs. I suppose with the update provided this issue could be closed.
