### ISSUE TITLE
Override key mapping after app is launched

### ISSUE THREAD

**Issue by darioRandazzoAccedo** [rdkcentral/Lightning-SDK#276]
Hello,
is it possible to setup the key mapping **after** the app is launched? Reading the lightning sdk, it seems the keys register can happen only inside the Application class' constructor, no way to invoke this with a public method.

**Comment by michielvandergeest** [comment]
Thanks for your patience on this issue @darioRandazzoAccedo 

Would you be able to provide a bit more context on how you would want to change the keymapping after app launch? Are you looking to change it from within the app context? or from the outside in?

**Comment by darix989** [comment]
Hello,
our pipeline would be:

1. LNG (sync) launch;
2. async launch of another library;
3. once this library is loaded, we use one of its functions that will provide us the key mapping for the current platform;
4. now we would call whatever LNG function that will let us override the app key mapping (we are missing this last step at the moment).

I hope the workflow is clear.

Thanks!
