### ISSUE TITLE
Porting custom video player in Lightning SDK

### ISSUE THREAD

**Issue by krackjack234** [rdkcentral/Lightning-SDK#277]
Hi,

Is there anyway we can port a custom video player in Lightning SDK and use/augment the standard Videplayer apis (https://rdkcentral.github.io/Lightning-SDK/#/plugins/videoplayer)?

We want to add a custom player to enhance current Videoplayer capabilities like playing drm and ads and collecting custom metrics information.

Please let us know if this is achievable.

**Comment by krackjack234** [comment]
hi, anyone has any pointers about this?

**Comment by erikhaandrikman** [comment]
This is highly achievable; The `VideoPlayer` plugin is nothing more then a bit of abstraction for the `HTMLVideoElement` https://github.com/rdkcentral/Lightning-SDK/blob/6d239403a40c4f53ea1054ebd79124e712102ea1/src/MediaPlayer/index.js#L94

If your app needs more advanced functionality like DRM protected content we highly encourage you to build (or port) your own player and where needed use `VideoPlayer` methods: https://rdkcentral.github.io/Lightning-SDK/#/plugins/videoplayer?id=available-methods
