### ISSUE TITLE
How to Play Drm Content 

### ISSUE THREAD

**Issue by googleboy0** [rdkcentral/Lightning-SDK#286]

**Comment by wouterlucas** [comment]
Lightning or Lightning-SDK does not provide DRM decryption mechanisms. 

You can use the browser's standard implementation of EME:
https://www.w3.org/TR/encrypted-media/
https://developer.mozilla.org/en-US/docs/Web/API/Encrypted_Media_Extensions_API

Or a good introduction to EME is:
https://www.html5rocks.com/en/tutorials/eme/basics/

However your device/machine needs to support the DRM you're trying to play. So for example if you are trying to play PlayReady 2.5 protected content your browser needs to have a PlayReady implementation that hooks up to EME in oder for the decryption to work.
