### ISSUE TITLE
How do I run the Lightning app on the RDK-emulator?

### ISSUE THREAD

**Issue by nitch193** [rdkcentral/Lightning-SDK#295]
I followed the guide on [this](https://github.com/Metrological/rdk-emulator) github repo of Metrological platform I was able to build the emulator on my local system using Virtual box. Also I was also able to run the maf3-sdk demo app as as it was explained in the guide. But when I tried to close the maf3-sdk demo app and run my lightning app on the emulator it shows only a blank white page, When i tried the web inspector of the rdk-emulator it shows that it has correctly loaded the startApp.js code but shows the error - ReferenceError: Can't find variable: Promise. So I think if this issue get solved the app will run on emulator.

**Comment by erikhaandrikman** [comment]
Assuming that you're using `Lightning CLI`, did you build your bundle via `lng dist`? 
https://lightningjs.io/docs/#/lightning-cli-reference/Commands/dist

From the looks of the error you're probably running in a environment that doesn't have support for `Promises`, so you need to ship a polyfill or try to transpile your appbundle: `lng dist --es5`

**Comment by michielvandergeest** [comment]
On top of that, the RDK emulator project you are referring to is outdated, and unless you have a specific use case I don't think it should be used for test Lightning Apps. Instead run your apps on a real device or check out the RDK reference platform details: https://wiki.rdkcentral.com/display/RDK/RDK+Reference+Platform
