### ISSUE TITLE
How we can fix the height of our list so that it won't scroll beyond that height

### ISSUE THREAD

**Issue by googleboy0** [rdkcentral/Lightning-SDK#299]
![image](https://user-images.githubusercontent.com/54769987/154096112-f8e03b60-fd47-4f2a-ad28-9dc2b4773c91.png)
In this above image, the items are going above the Text, i want they should become invisible when started scrolling

**Comment by michielvandergeest** [comment]
hey @googleboy0, the effect you're looking for is definitely possible to achieve with Lightning. But it's probably best to ask these kind of support questions at our [Lightning forum](https://forum.lightningjs.io/) :)

**Comment by googleboy0** [comment]
Thanks for the fast response i will try over there

**Comment by googleboy0** [comment]
> hey @googleboy0, the effect you're looking for is definitely possible to achieve with Lightning. But it's probably best to ask these kind of support questions at our [Lightning forum](https://forum.lightningjs.io/) :)

could you tell me how to achieve that, effect, is there any method or any attribute, or do i need to make visible false the above items? i need to showcase the product this week, so i need to resolve this problem ASAP

I did try posting queries in Lightning forum but the account is on temporarily blocked.
