### ISSUE TITLE
SDK Colors utility calculations

### ISSUE THREAD

**Issue by mauro1855** [rdkcentral/Lightning-SDK#302]
Hi,

I am developing a project with the LightningJS SDK and just started using the Colors utility, but it seems I may have a found a bug in the calculations done by the Colors utility.

In order to get a 50% opacity white, I was previously hardcoding 0x80ffffff, since 80 corresponds to 50% opacity according to this: https://gist.github.com/lopspower/03fb1cc0ac9f32ef38f4
However, when I replace this with Colors('white').alpha(0.5).get(), it calculates 7fffffff. Calculated opacity is 7F instead of 80. This is a very small error margin, potentially related to rounding or floating point calculations, but an error nonetheless and my colleagues thought I should report it.

Can you take a look?
I'm using SDK version 4.8.1

**Steps to reproduce**
Colors('white').alpha(0.5).get()

**Expected Behaviour**
Return value should be 80FFFFFF

**Actual Behaviour**
Return value is 7FFFFFFF

**Comment by michielvandergeest** [comment]
This is fixed and released (v4.8.2)
