### ISSUE TITLE
Problem in supporting dynamic resolutions other than 1920x1080

### ISSUE THREAD

**Issue by suryaltts** [rdkcentral/Lightning-SDK#311]
Explaining with an code example,

```
return Launch(
App,
{
stage: {
clearColor: ‘0x00000000’,
useImageWorker: true,
},
debug: true,
hls: true,
},
{
path: ‘./static’,
log: true,
showVersion: false,
inspector: false,
showFps: false,
width: 300,
height: 800,
}
)
```

The above values for w and h we are passing as platformSettings to Application but it still takes in 1920x1080
Because of the above configuration/hardcoded dimensions, we get to see white area around the content. Also the screen is scrolling with the free content.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/47888887/161565031-3a6ced51-a933-49d4-9109-fb756c2d99b2.png)

**Comment by sandeep-vedam** [comment]
Hi @suryaltts,

This issue is fixed and released in Lightning SDK Version 5.2.0
