### ISSUE TITLE
Deeplinks break in 4.8.0

### ISSUE THREAD

**Issue by yvbeek** [rdkcentral/Lightning-SDK#321]
In our app we use deep-links so that we can send the user to a specific show or episode. This was working well, but it is no longer working after we've upgraded to 4.8.0.

I noticed that deep-links are still working for known routes (those that have been passed to `Router.startRouter`), but we are using a fallback mechanism that if the deep-link is not a known route, that we grab that page from our CMS and display the content in our app. This no longer works in 4.8.0.

**Edit:** the commit that seems to break our functionality is: https://github.com/rdkcentral/Lightning-SDK/commit/2957ad1c6a087ad64a0bd6266e05799c22a9d4b3
**Edit 2:** after more testing it seems that version 4.4.0 also broke part of this functionality:
https://github.com/rdkcentral/Lightning-SDK/blob/master/CHANGELOG.md#v440

**Comment by michielvandergeest** [comment]
Hi @yvbeek, is this still an issue? Or can we close this?
