### ISSUE TITLE
VideoTexture position animation is inconsistent

### ISSUE THREAD

**Issue by mauro1855** [rdkcentral/Lightning-SDK#326]
Hi Lightning SDK team,

I created recently a little project to see how I could create "video thumbnails" that start playing when I focus the element - it involved punching a hole in the canvas (with the HoleShader) and changing the position and size of the VideoPlayer (with `VideoPlayer.position()` and `VideoPlayer.size()` methods)

But I found that the `VideoPlayer.position()` behaviour is not consistent when `textureMode` is turned on or off. 
* If textureMode is turned off, the style is updated and the video player tag "jumps" to the location.
* If textureMode is turned on, the texture is "smoothed" into the location, thus causing a delay until it actually reaches there. This means that, with the a hole punched in the canvas, you can see the video texture sliding into place.

I find this behaviour difference between texture and non-texture mode to be inconsistent, and provides an unpredictable and uncontrollable experience to developers. Not only with the `VideoPlayer.position()` method, but with the `.size()`, `.show()` and `.hide()` methods as well - the VideoTexture animates / smooths all of them, while the video tag is directly assigned the CSS style which takes effect immediately without animation. Besides being inconsistent, it is rather opinionated as well; it assumes the developer wants the smooth effect, while it might not be the case.

You can find the relevant code [here](https://github.com/rdkcentral/Lightning-SDK/blob/805784b1361148b36deea9f8b12a00eb834e22e4/src/VideoPlayer/index.js#L203) and [here](https://github.com/rdkcentral/Lightning-SDK/blob/93c749509bb9a5db5e2888b8eed7d76ab3ac72ec/src/VideoPlayer/VideoTexture.js).

Would you consider a PR to remove the smoothness out of the video texture?

Best regards,
Mauro

**Comment by michielvandergeest** [comment]
Hi @mauro1855, thanks for your report.

Starting v5.0.0 the VideoPlayer plugin is no longer part of the Lightning-SDK. It’s been moved to the [Metrological-SDK](https://github.com/Metrological/metrological-sdk).

I’m not able to move issues between organizations, so I would suggest to open this issue as a new ticket [over here](https://github.com/Metrological/metrological-sdk/issues).
