### ISSUE TITLE
playAfterSeek in VideoPlayer not working

### ISSUE THREAD

**Issue by mauro1855** [rdkcentral/Lightning-SDK#328]
Hi SDK team,

The VideoPlayer plugin currently has some logic on `seek()` to resume video playback if it was already playing when `seek()` was called. You can find the logic [here](https://github.com/rdkcentral/Lightning-SDK/blob/master/src/VideoPlayer/index.js#L322) and then [here](https://github.com/rdkcentral/Lightning-SDK/blob/master/src/VideoPlayer/index.js#L76).

Unfortunately this is currently not working - the playback doesn't resume. I checked with @bjornvanspengen and @tomvdbroek and we believe the issue lies in the fact that the `play()` is called before the video player is ready to play after the seek. 

I think the player needs to wait for the `canplay` player event before it can play. I will be submitting a PR with this solution soon.

**Comment by michielvandergeest** [comment]
Hi @mauro1855, thanks for your report.

Starting v5.0.0 the VideoPlayer plugin is no longer part of the Lightning-SDK. It’s been moved to the [Metrological-SDK](https://github.com/Metrological/metrological-sdk).

I’m not able to move issues between organizations, so I would suggest to open this issue as a new ticket [over here](https://github.com/Metrological/metrological-sdk/issues).
