### ISSUE TITLE
VideoPlayer gets width and height from platformSettings

### ISSUE THREAD

**Issue by ricardo-a-alves-alb** [rdkcentral/Lightning-SDK#331]
According to [RuntimeConfiguration](https://lightningjs.io/docs/#/lightning-core-reference/RuntimeConfig/index), the width and height of the viewport is defined on the [Stage Configuration](https://lightningjs.io/docs/#/lightning-core-reference/RuntimeConfig/index?id=stage-configuration-options) using the `w` and `h` parameters.

However, in the VideoPlayer plugin, it is trying to read width and height from the `platformSettings`. I believe this is not intended. I will provide a PR fixing this.

https://github.com/rdkcentral/Lightning-SDK/blob/82b8948ca0e7efe7afe5a94ba5700d21a9cc880c/src/VideoPlayer/index.js#L127-L132

**Comment by michielvandergeest** [comment]
Hi @ricardo-a-alves-alb, thanks for your report.

Starting v5.0.0 the VideoPlayer plugin is no longer part of the Lightning-SDK. It’s been moved to the [Metrological-SDK](https://github.com/Metrological/metrological-sdk).

I’m not able to move issues between organizations, so I would suggest to open this issue as a new ticket [over here](https://github.com/Metrological/metrological-sdk/issues).
