### ISSUE TITLE
Pixeled fonts in Metrological build

### ISSUE THREAD

**Issue by mikita-liaukovich-epam** [rdkcentral/Lightning-SDK#334]
Hi guys,

I've encountered issue with some fonts in Metrological build (only): some fonts are rendering pixeled, but some are smooth.
E.g.:
![image](https://user-images.githubusercontent.com/43153354/178691125-b1012903-4296-4dba-a4b6-6890c5f799da.png)

Both labels share the same properties as they are the same components and rendering in the Array.prototype.map

Here is the template
```js
static _template() {
    return {
      flex: {
        direction: "row",
        alignItems: "center",
      },
      Title: {
        flexItem: {
          marginLeft: MARGIN_LEFT,
        },
        text: {
          fontSize: 30,
          fontStyle: "bold",
          fontFace: fonts.VMCircularYell_Black,
          wordWrapWidth: SIZE.w - (MARGIN_LEFT * 2),
          lineHeight: 35,
        },
      },
    };
  }
```

Just an observation: in that exact case pixeled label is wrapped (wordWrap), the smooth one isn't

But the same issue appears in other places, like this one:

<sub>Don't mention the color, there's no dependency on color property</sub>

![image](https://user-images.githubusercontent.com/43153354/178689649-566684ec-5023-4381-81a2-3c3aa010699f.png)
![image](https://user-images.githubusercontent.com/43153354/178689663-5de587c1-eb9a-4fad-8bb1-1407b1c360c0.png)

**SDK: 4.8.1
CLI: 2.7.2
Build: Metrological only
Seen on: Arris EOS, Humax EOS
Browser: WPE**

**Comment by wouterlucas** [comment]
Hi @mikita-liaukovich-epam does this happen on a dist build as well or just in the metrological environment?

If it happens on a dist build too, can you share a snippit or sample app that reproduces the issue so we can have a look?
