### ISSUE TITLE
App configuration, loading on file:// protocol

### ISSUE THREAD

**Issue by PaulRotar93** [rdkcentral/Lightning-SDK#347]
Hi!

By attempting to run the app on a file protocol (default used by Tizen devices), I've noticed that the settings.json and metadata.json files are being disallowed from being fetched.

Is there any possibility to have these files configurable in a way that as a developer I can choose not to use an external runtime configuration and opt for a bundled/built-in approach without having the build fail?

E.G.
`export default () => Launch(App, Settings.appSettings, Settings.platformSettings);`

Thanks!

**Comment by michielvandergeest** [comment]
Hi @PaulRotar93 I think you may be better served with a _distributable_ version of your App. You can generate one by running the `lng dist` command.

This will create a build of your app and an index.html file in the dist folder of your project. It does not rely on `metadata.json` and `settings.json` being present (they are being used for the first generation though) and has all the settings and info inline in the html file.

Hope that helps.
