### ISSUE TITLE
Router UpdateHash not working

### ISSUE THREAD

**Issue by mauro1855** [rdkcentral/Lightning-SDK#348]
Hi Lightning SDK team,

As far as I can tell, the `updateHash` router setting is not currently doing anything. No matter if I set it to true or false, the hash is always updated in the URL.

**Steps to replicate**:
1. Download the [router-example-app](https://github.com/mlapps/router-example-app)
2. Change router settings in the `settings.json` file so that `"updateHash": false`
3. Start the app with `lng dev`.

**Expected behaviour:**
The URL hash should not be updated when routes change. (is that correct?)

**Observer behaviour:**
The URL hash is updated when the route changes. Changing the `updateHash` property has no effect.

**Comment by michielvandergeest** [comment]
Hi @mauro1855 thanks for this report.

We have indeed confirmed that the updateHash option doesn't have any effect.

@sandeep-vedam can you look into a fix for this?

**Comment by michielvandergeest** [comment]
This one has been merged and will be released in our upcoming October release.
