### ISSUE TITLE
App version wrongly positioned

### ISSUE THREAD

**Issue by mauro1855** [rdkcentral/Lightning-SDK#359]
Hi Lightning SDK team,

Since Lightning SDK 5.2.0, the app version is wrongly position for apps that are set to run in 1280x720 (0.6667 precision). See here a screenshot:

<img width="956" alt="image" src="https://user-images.githubusercontent.com/18258655/201885250-526f18dd-9b06-48eb-b111-0d306a5cb82d.png">

**Steps to reproduce:**
1. Create a new Lightning app with the CLI (`lng create`)
2. Add the following `stage` settings to the `setting.json` file:
```
"w": 1280,
"h": 720,
"precision": 0.66667
```

**Expected behaviour:**
The app version's blue rectangle should be positioned in the bottom right corner, as it has been in previous Lightning SDK versions.

**Observed behaviour:**
The app version's blue rectangle positioning is not correct.

**Happens since:** 5.2.0

**Comment by michielvandergeest** [comment]
Thanks for reporting this. We're looking into it!
