### ISSUE TITLE
[Support] Control over the video's dimensions and positioning

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [rdkcentral/Lightning-SDK#46]
Is possible to have control over dimensions and positioning of the video element?

**Comment by michielvandergeest** [comment]
You can control both the size and the position of the video player with the `_setVideoArea` function.

```js
const top = 0
const left = 0
const width = 1920
const height = 1080

this.tag('MediaPlayer')._setVideoArea([top, left, width, height])
```

This should be documented. Keeping this issue open for now.

**Comment by michielvandergeest** [comment]
Fixed.
