### ISSUE TITLE
Align SRC and DOCS Media Player Events

### ISSUE THREAD

**Issue by MattiaPontonioKineton** [rdkcentral/Lightning-SDK#47]
Can You please check and align the Events documented and effectivly fired by the `MediaPlayer`?
https://webplatformforembedded.github.io/Lightning-SDK/#/plugins/mediaplayer?id=events
For example I've used `$mediaplayerProgress` but seems that is documented ad `$mediaplayerTimeupdate`.
Can I suppose to use all the `$mediaplayer{Event}` that I find in the class in `master`?

**Comment by michielvandergeest** [comment]
Fixed.
