### ISSUE TITLE
HLS support in Media Player

### ISSUE THREAD

**Issue by jessfdm-codes** [rdkcentral/Lightning-SDK#51]
Hi, 

I was wondering if there was any plans to implement support for HTTP Live Streams for the Media Player? Normally this has to be done using an external library for something like Chrome (HLS.js for example), if the above isn't the case is there a recommended way to access the Video tag itself and call functions on it bypassing Lightning's abstraction behind the MediaPlayer type, in order to use something like HLS.js?

Cheers

**Comment by erikhaandrikman** [comment]
Maybe we can expose the functionality via the SDK in the future, but for now you need to include hls.js yourself to your project. You're able to grab a reference to the video-tag via: 

```
import {Lightning, MediaPlayer} from 'wpe-lightning-sdk';

export default class Player extends Lightning.Component {
   static _template(){
    return {
     MediaPlayer:{  type: MediaPlayer },
     Controls: { ... }
    }
  }
  
 _init(){
    // get ref to video-tag
    cont el = this.tag("MediaPlayer").videoEl;
  } 
}
``` 

or something like: `const el = document.getElementsByTagName("video")[0];` 

Once you have a reference to the video-tag you can create a new instance of `Hls` and call the right methods: 

```
const hlsPlayback = new Hls({liveDurationInfinity: true});
hlsPlayback.loadSource(src);
hlsPlayback.attachMedia(this.videoEl);
```

**Comment by thomasfdm** [comment]
Cheers for this, is it possible to turn off the metrics for the MediaPlayer? It seems to be throwing errors because the Metric tool cannot understand the url and thus the _registerListeners() function gives me the following error:

```
Uncaught TypeError: Cannot read property 'timeupdate' of null
    at HTMLVideoElement.handler (index.js:89)
```

Along with quite a few other errors that are the same apart from `timeUpdate` being something like `play` or `seeking`.

**Comment by AlexV4A** [comment]
Hi,
I have got the Streaming URL (m3u8 format) played with SDK2, as soon as i got the latest SDK2. Here are the steps, i did to make it happen, (Please correct me if i go wrong)

1. Added the hls (latest) file to the application.
2. In Settings.json -> appSettings -> there is an option for hls, for which i gave the value true.
3. Inside SDK - MediaPlayer.js - added the code  this._metrics = Metrics.media(settings.stream.src). To give support to the metirc object.
4. Inside Application on init added the code window.Hls = Hls;
5. Finally in Player component that i developed, gave this code to add stream url to Media instance.
this.tag('MediaPlayer').updateSettings(
      {
        consumer: this, 
        stream : { src : videoUrl},
        videoPos : [0, 0, 1920, 1080]
      });

**Comment by thomasfdm** [comment]
Ah cool, looking at the source for MediaPlayer there seems to be basically the same code as I've written based off of @erikhaandrikman's comment. 

Is there documentation about the settings available for the MediaPlayer? The code also says 
```
        // This is here to be backwards compatible, will be removed
        // in future sdk release
```
(src/MediaPlayer/index.js:231)

Does that mean the built-in streaming functionality in SDK 2.x will be removed all together at some point?
