### ISSUE TITLE
Remote tv controller

### ISSUE THREAD

**Issue by pabioFavanetto** [rdkcentral/Lightning-SDK#54]
Hello,
after reading the metrological documentation
 I saw that it is possible to create a remote tv controller with a smartphone, is it possible to recreate a demo with l
Lightning-SDK? if yes, how? can you suggest me where to start.

**Comment by mattiapontonio** [comment]
Minimum setup:
- 1 Web App in Lightining for the TV
- 1 Web or Native App in Lightining (not suggested) or not for the Smartphone
- 1 or more Node JS servers (or others technology) that serves the two web apps and manages communication

It's a fullstack application. I think that Lightining SDK is not enaught to fit this need.

Consider even that every browser manages our instance of the application so You need a server.
