### ISSUE TITLE
Unable to set textureMode:true in settings.json

### ISSUE THREAD

**Issue by KadeejaBai** [rdkcentral/Lightning-SDK#72]
I'm unable to set the textureMode via settings.json file.It works when passed as a queryparam
`{
  "appSettings": {
    "stage": {
      "clearColor": "0x00000000",
      "useImageWorker": true
    },
    "debug": false
  },
  "platformSettings": {
    "inspector": true,
    "textureMode": true,
    "path": "./static"
  }
}`

**Comment by michielvandergeest** [comment]
Yes, that seems to be a bug. Thanks!
Will be fixed in the next release. For now you can indeed pass `?texture` as a query param as temporary workaround.

**Comment by michielvandergeest** [comment]
@KadeejaBai this should now be fixed in v2.3.0
