### ISSUE TITLE
Installing without Lightning-CLI

### ISSUE THREAD

**Issue by mattiapontonio** [rdkcentral/Lightning-SDK#73]
Can You please provide an example of installing without the use of Lightning-CLI?
For example, this should be "safe"?
```
"dependencies": {
        "wpe-lightning-sdk": "git+https://github.com/WebPlatformForEmbedded/Lightning-SDK.git#2.2.0"
 }
```

**Comment by michielvandergeest** [comment]
yes, the CLI merely creates an App blueprint for you with a package.json that has `wpe-lightning-sdk` as a dependency.

You can do that yourself as well. So your example is perfectly valid.
